### PR TITLE
Rewritev2/typescript

### PR DESCRIPTION
**Pull request by Sayykii**
This pull request is related to #7

### CODE REVIEW

**Comment by xrexy** [comment]
W mans

**Comment by Sayykii** [comment]
@dependabot

**Review by crackheadakira — CHANGES_REQUESTED** [review]
Not biased at all, but everything seems to check out properly. Though you need to tell users how to make a DB in the README.md

**Comment by Sayykii** [comment]
> Not biased at all, but everything seems to check out properly. Though you need to tell users how to make a DB in the README.md

Yeah you're right, will update the readme asap

**Review by TibixDev — APPROVED** [review]
LGTM! 🙌

**Review by TibixDev — APPROVED** [review]

**Pull request merged**
